version: "3"
services:
  localstack:
    image: localstack/localstack
    container_name: my_localstack
    ports:
      - 4566:4566
      - 8080:8080
    environment:
      - DEFAULT_REGION=ap-northeast-1
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack:/tmp/localstack/